name: Testing
on:
  - push
  - workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: job
    steps:
      - name: ArchDocker
        uses: Petkr/PParchdocker@latest
        with:
          script_name: build.sh
          packages: gcc cmake ninja
