name: Testing
on:
  - push
  - workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: job
    steps:
      - name: ArchDocker
        uses: Petkr/PParchdocker@latest
        with:
          repo_url: https://github.com/Petkr/PP.git
          script_name: test.sh
          packages: gcc cmake ninja
