name: Testing
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ArchDocker
        uses: Petkr/PParchdocker@v1.0.0
        with:
          script_and_packages:
            - build.sh
            - gcc
            - cmake
            - ninja
