name: Testing
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ArchDocker
        uses: Petkr/PParchdocker@00cc05c251984bea67b2a88063281d92cf704cc0
        with:
          script_name: build.sh
          packages: gcc cmake ninja
