name: Testing
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ArchDocker
        uses: Petkr/PParchdocker@7d5dba5954112c611955c2454da151b7767c8a92
        with:
          script_name: build.sh
          packages: gcc cmake ninja
