name: Testing
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: job
    steps:
      - name: ArchDocker
        uses: Petkr/PParchdocker@e0d060b181fa82e9b03d0d8add04c55fa168d11c
        with:
          #repo: Petkr/PP
          script_name: build.sh
          packages: gcc cmake ninja
